### ISSUE TITLE
Sitemap <lastmod> value possibly incorrect

### ISSUE THREAD

**Issue by kuopassa** [gocom/rah_sitemap#9] opened 2022-09-12 02:55 UTC
In version 3.0.0 the code `safe_strftime('iso8601', $modifiedAt);` creates a timestamp that ends with 4 digits, like 0000, but I think the correct format is to have a colon like this: 00:00.

**Comment by gocom** [comment] 2022-09-12 15:56
Thank you for the report :) 

This appears to be a regression in Textpattern 4.8.8. In Textpattern 4.8.7 and earlier `safe_strftime('iso8601', $modifiedAt);` used to generate format such as `2022-01-01T12:15:15Z`.

Implementation in 4.8.7:
https://github.com/textpattern/textpattern/blob/4.8.7/textpattern/lib/txplib_misc.php

In 4.8.8, Texpattern migrated from the deprecated strftime to date, which added a wrapping around the old supported format strings, but at the same time added changes to it:
https://github.com/textpattern/textpattern/blob/4c36c0506ad13387f518166574f8a0006aa1effc/textpattern/lib/txplib_misc.php#L2721

Due to ISO-8601 being rather poor, it can have different format implementations. To keep backwards compatibility, the format used in the Textpattern core should be `c` instead of the `DATE_ISO8601` constant.

If you want, you could also open a bug report to Textpattern, so they can fix the root cause. I will regardless mitigate this by changing from the current format value to `c`.

**Comment by gocom** [comment] 2022-09-12 16:07
Fixed by 7834c7189f13b46d630fba3c3e50fd4b8b05b857

**Closed by gocom** 2022-09-12 16:07 UTC
Labels: Bug, Investigate
